name: tools.shenzjd.com CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout repo
        uses: actions/checkout@v3
      # setup-qumu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # setup docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      # 构建 Docker 镜像
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tools.shenzjd.com:$(date +%s)
      # 保存镜像
      - name: Save image
        run: docker save -o /docker/tools.shenzjd.com-$(date +%s).tar tools.shenzjd.com:$(date +%s)
      # 上传到服务器
      - name: Upload to Deploy Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "106.55.242.160"
          port: "21"
          local-dir: ./docker/
          username: tools_shenzjd_com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
